[package]
name = "embedded-rforest"
version = "0.1.0"
edition = "2024"

[dependencies]
aligned-vec = { version = "0.6.1", optional = true }
heapless = "0.8.0"
type-layout = { version = "0.2.0", optional = true }
zerocopy = { version = "0.8.7", features = ["derive"] }

[dev-dependencies]
anyhow = "1.0.91"

[features]
std = ["dep:aligned-vec", "dep:type-layout"]

[[bin]]
name = "type_layout"
required-features = ["std"]
